#!/bin/bash

# A script to setup my config files

DOTFILES="$( ls -a .* )"
echo "Installing the following files in $HOME:"
for f in $DOTFILES; do
  echo "  $f"
  ln -sf "$PWD/$f" "$HOME/$f"
done

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/alacritty

ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml
