return {
    { "hrsh7th/nvim-cmp", enabled = false },
    { "hrsh7th/cmp-nvim-lsp", enabled = false },
    { "hrsh7th/cmp-buffer", enabled = false },
    { "hrsh7th/cmp-path", enabled = false },
    { "L3MON4D3/LuaSnip", enabled = false },
    { "rafamadriz/friendly-snippets", enabled = false },
    { "nvim-cmp", enabled = false },
    { "saadparwaiz1/cmp_luasnip", enabled = false },
    { "echasnovski/mini.pairs", enabled = false },
    { "echasnovski/mini.surround", enabled = false },
    { "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
    { "echasnovski/mini.comment", enabled = false },
    { "echasnovski/mini.ai", enabled = false },
    { "folke/flash.nvim", enabled = false },
    { "RRethy/vim-illuminate", enabled = false },
    { "windwp/nvim-ts-autotag", enabled = false },
    { "folke/noice.nvim", enabled = false },
}
