#!/bin/bash

user_home="/home/mike"
key="$user_home/.ssh/backup.key"
src="/media/external/Backups/arch-sync"
dst="/media/containers/arch-sync"
targets=(
    ".keepass/passwords.kdbx"
    "notes"
    "Desktop/important-docs"
)

# ~~~~~~~~~~~~~~~ checking network ~~~~~~~~~~~~~~~~~~~~~~~~

if ! ping -c 3 -w 10 rpi3 &> /dev/null; then
    echo "[-] Network not available"
    exit 1
fi

# ~~~~~~~~~~~~~~~ mounting ~~~~~~~~~~~~~~~~~~~~~~~~

# Mount external drive
if ! mount | grep /media/external &> /dev/null; then
    echo "[*] Mounting external drive"
    if ! mount /media/external; then
        echo "[-] Drive not available"
        exit 1
    fi
fi

# Mount veracrypt container
if ! veracrypt --text --non-interactive --list ${dst} &> /dev/null; then 
    echo "[*] Mounting ${dst}"
    sudo veracrypt --text --non-interactive --password="" --keyfiles="$key" --mount ${src} ${dst} 
    if  [[ $? != 0 ]]; then
        echo "[-] Volume not available"
        exit 1
    fi
fi

# ~~~~~~~~~~~~~~~ unison ~~~~~~~~~~~~~~~~~~~~~~~~

# Backup files from source to destination
for f in "${targets[@]}"; do
    unison $user_home $dst -path "$f" -batch
    if  [[ $? != 0 ]]; then
        DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u mike)/bus notify-send "File conflicts when syncing '$f'"
    fi
done

# ~~~~~~~~~~~~~~~ unmounting ~~~~~~~~~~~~~~~~~~~~~~~~

# Unmount veracrypt container
echo "[*] Unmounting ${dst}"
sudo veracrypt -d ${dst}

