#!/bin/bash

# Change the system theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita"

# Change the alacritty theme
sed -i -e 's/everforest_dark.toml/everforest_light.toml/g' $LT/dotfiles/alacritty.toml

# Change neovim theme
sed -i -e 's/vim.o.background = "dark"/vim.o.background = "light"/g' $LT/dotfiles/nvim/init.lua

# Change the browser theme
find ~/.mozilla -name user.js -exec \
    sed -i -e 's/user_pref("layout.css.prefers-color-scheme.content-override", 0);/user_pref("layout.css.prefers-color-scheme.content-override", 1);/' {} \;

# Change abckground image for home desktop
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorDP-1-2/workspace1/last-image -s /usr/share/backgrounds/firewatch.jpg
