#!/bin/bash

# Change the alacritty theme
sed -i -e 's/gruvbox_dark.toml/gruvbox_light.toml/g' $LT/dotfiles/alacritty.toml

# Change neovim theme
sed -i -e 's/vim.o.background = "dark"/vim.o.background = "light"/g' $LT/dotfiles/nvim/init.lua

# Change the browser theme
find ~/.mozilla -name user.js -exec \
    sed -i -e 's/user_pref("layout.css.prefers-color-scheme.content-override", 0);/user_pref("layout.css.prefers-color-scheme.content-override", 1);/' {} \;

